server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: jarvis

  r2dbc:
    url: ${R2DBC_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${JDBC_URL:}
    user: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}

# ======= Management / Actuator =======
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      #      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          include: r2dbc # readinessState
        liveness:
          include: ping # livenessState
#  health:
#    defaults:
#      enabled: true


telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  webhook-secret: ${TG_WEBHOOK_SECRET:}
  webhook:
    base-path: /tg
    endpoint: /webhook

openai:
  token: ${OPENAI_TOKEN:}
proxy:
  host: ${PROXY_HOST:}
  port: ${PROXY_PORT:}
  user: ${PROXY_USER:}
  password: ${PROXY_PASSWORD:}

logging:
  level:
    ru.jarvis: DEBUG
    root: INFO
    org.springframework.web: INFO
    reactor.netty.http.client: WARN
    reactor.netty.http.server: WARN
